apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  name: wf-applying-cc-functions-v0
spec:
  entrypoint: dag-tasks
  templates:
  - name: dag-tasks
    dag:
      tasks:
      - name: task1
        template: mesh-to-cloudpoint

  - name: mesh-to-cloudpoint
    script:
      image: ifte110/cloudcompare-simple-artifact
      command: [bash]
      source: |
        xvfb-run CloudCompare -SILENT -AUTO_SAVE OFF -O /files/panel_artec_scan.obj -SAMPLE_MESH POINTS 100000 -SS SPATIAL 0.1 -SAVE_CLOUDS FILE output.bin
    outputs:
      artifacts:
      - name: outputfinal
        path: /files/output.bin
