apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  name: wf-applying-cc-functions-v2-copy
spec:
  entrypoint: dag-tasks
  templates:
  - name: dag-tasks
    dag:
      tasks:
      - name: task1
        template: mesh-to-cloudpoint
      - name: task2
        template: cloudpoint-subsampling
        dependencies: [task1]
        arguments:
          artifacts:
            - name: objectfinal
              from: "{{tasks.task1.outputs.artifacts.object2}}"
        
  - name: mesh-to-cloudpoint
    inputs:
      artifacts:
      - name: object
        path: /files/panel_artec_scan.obj
        s3:
          # Use the corresponding endpoint depending on your S3 provider:
          #   AWS: s3.amazonaws.com
          #   GCS: storage.googleapis.com
          #   Minio: my-minio-endpoint.default:9000
          bucket: my-bucket
          endpoint: minio:9000
          key: /my-bucket/panel_artec_scan.obj
          # accessKeySecret and secretKeySecret are secret selectors.
          # It references the k8s secret named 'my-s3-credentials'.
          # This secret is expected to have have the keys 'accessKey'
          # and 'secretKey', containing the base64 encoded credentials
          # to the bucket.
          accessKeySecret:
            name: my-minio-cred
            key: accessKey
          secretKeySecret:
            name: my-minio-cred
            key: secretKey
    script:
      image: ifte110/cloudcompare-simple
      command: [bash]
      source: |
        xvfb-run CloudCompare -SILENT -AUTO_SAVE OFF -O /files/panel_artec_scan.obj -SAMPLE_MESH POINTS 1000 -SAVE_CLOUDS FILE /files/output.bin
    outputs:
      artifacts:
      - name: object2
        path: /files/output.bin

  - name : cloudpoint-subsampling
    inputs:
      artifacts:
        - name: objectfinal
          path: /files/output.bin
    script:
      image: ifte110/cloudcompare-simple
      command: [bash]
      source: |
        xvfb-run CloudCompare -SILENT -AUTO_SAVE OFF -O  /files/output.bin -SS SPATIAL 0.1 -SAVE_CLOUDS FILE /files/output2.bin
    outputs:
      artifacts:
      - name: outputfinal
        path: /files/output2.bin
    
