apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  name: wf-applying-cc-functions-v1
spec:
  entrypoint: dag-tasks
  templates:
  - name: dag-tasks
    dag:
      tasks:
      - name: task1
        template: mesh-to-cloudpoint
      - name: task2
        template: cloudpoint-subsampling
        dependencies: [task1]
        arguments:
          artifacts:
            - name: objectfinal
              from: "{{tasks.task1.outputs.artifacts.outputfinal}}"

  - name: mesh-to-cloudpoint
    script:
      image: ifte110/cloudcompare-simple-artifact
      command: [bash]
      source: |
        xvfb-run CloudCompare -SILENT -AUTO_SAVE OFF -O /files/panel_artec_scan.obj -SAMPLE_MESH POINTS 100 -SAVE_CLOUDS FILE /files/output.bin
    outputs:
      artifacts:
        - name: outputfinal
          path: /files/output.bin

  - name : cloudpoint-subsampling
    inputs:
      artifacts:
        - name: objectfinal
          path: /files/output.bin
    script:
      image: ifte110/cloudcompare-simple-artifact
      command: [bash]
      source: |
       xvfb-run CloudCompare -SILENT -AUTO_SAVE OFF -O  /files/output.bin -SS SPATIAL 0.1 -SAVE_CLOUDS FILE /files/output2.bin
    outputs:
      artifacts:
      - name: outputfinal
        path: /files/output2.bin
        